flowchart LR
    subgraph docs__DEFSCAN
        docs__DEFSCAN__print["print"]
    end
    subgraph regres__defscan
        regres__defscan__render_seed_json["render_seed_json"]
        regres__defscan___def_key["_def_key"]
        regres__defscan__extract_rust["extract_rust"]
        regres__defscan__render_seed_text["render_seed_text"]
        regres__defscan___analyse_and_sort_groups["_analyse_and_sort_groups"]
        regres__defscan___count_similarity_levels["_count_similarity_levels"]
        regres__defscan__sim["sim"]
        regres__defscan___run_focus_mode["_run_focus_mode"]
        regres__defscan___extract_block_ts["_extract_block_ts"]
        regres__defscan___match_anchored_pattern["_match_anchored_pattern"]
        regres__defscan___run_seed_mode["_run_seed_mode"]
        regres__defscan___advance_past_string["_advance_past_string"]
        regres__defscan__render_seed_markdown["render_seed_markdown"]
        regres__defscan__compare_seed_to_all["compare_seed_to_all"]
        regres__defscan___get_decorators["_get_decorators"]
        regres__defscan___short_path["_short_path"]
        regres__defscan___normalize["_normalize"]
        regres__defscan__extract_typescript["extract_typescript"]
        regres__defscan___print_pair_summary["_print_pair_summary"]
        regres__defscan___match_unanchored_pattern["_match_unanchored_pattern"]
        regres__defscan__extract_file["extract_file"]
        regres__defscan___run_default_mode["_run_default_mode"]
        regres__defscan___extract_class_definitions["_extract_class_definitions"]
        regres__defscan__analyse_group["analyse_group"]
        regres__defscan__scan["scan"]
        regres__defscan__Definition____init__["__init__"]
        regres__defscan__extract_python["extract_python"]
        regres__defscan___build_focus_groups["_build_focus_groups"]
        regres__defscan__classify_similarity["classify_similarity"]
        regres__defscan__c["c"]
        regres__defscan___lineno_at["_lineno_at"]
        regres__defscan__render_text["render_text"]
        regres__defscan__load_gitignore["load_gitignore"]
        regres__defscan__main["main"]
        regres__defscan__extract_go["extract_go"]
        regres__defscan___should_skip_file["_should_skip_file"]
        regres__defscan___get_body["_get_body"]
        regres__defscan__render_json["render_json"]
        regres__defscan___build_argument_parser["_build_argument_parser"]
        regres__defscan___path_ignored_by_gitignore["_path_ignored_by_gitignore"]
        regres__defscan___extract_function_definition["_extract_function_definition"]
        regres__defscan___collect_class_method_ids["_collect_class_method_ids"]
        regres__defscan___advance_past_comment["_advance_past_comment"]
    end
    subgraph regres__doctor_cli
        regres__doctor_cli___apply_fixes_if_requested["_apply_fixes_if_requested"]
        regres__doctor_cli___run_llm_or_targeted_analysis["_run_llm_or_targeted_analysis"]
        regres__doctor_cli___run_module_loader_compliance_check["_run_module_loader_compliance_"]
        regres__doctor_cli___append_url_module_not_found_diagnosis["_append_url_module_not_found_d"]
        regres__doctor_cli___run_vite_runtime_probe["_run_vite_runtime_probe"]
        regres__doctor_cli___create_import_chain_diagnoses["_create_import_chain_diagnoses"]
        regres__doctor_cli___handle_module_resolution["_handle_module_resolution"]
        regres__doctor_cli___record_url_discovery_step["_record_url_discovery_step"]
        regres__doctor_cli___setup_url_analysis_context["_setup_url_analysis_context"]
        regres__doctor_cli___save_report["_save_report"]
        regres__doctor_cli___record_module_not_found_step["_record_module_not_found_step"]
        regres__doctor_cli___refresh_import_error_log["_refresh_import_error_log"]
        regres__doctor_cli___handle_auto_decision_flow["_handle_auto_decision_flow"]
        regres__doctor_cli___derive_vite_base["_derive_vite_base"]
        regres__doctor_cli___resolve_module_from_url["_resolve_module_from_url"]
        regres__doctor_cli__main["main"]
        regres__doctor_cli___run_page_implementation_analysis["_run_page_implementation_analy"]
        regres__doctor_cli___run_url_module_analysis["_run_url_module_analysis"]
        regres__doctor_cli___resolve_runtime_log_path["_resolve_runtime_log_path"]
        regres__doctor_cli___run_dependency_chain_analysis["_run_dependency_chain_analysis"]
        regres__doctor_cli___collect_dependency_chain_targets["_collect_dependency_chain_targ"]
        regres__doctor_cli___handle_url_mode["_handle_url_mode"]
        regres__doctor_cli___handle_runtime_log_diagnostics["_handle_runtime_log_diagnostic"]
        regres__doctor_cli___run_page_registry_compliance_check["_run_page_registry_compliance_"]
        regres__doctor_cli___record_module_resolution_step["_record_module_resolution_step"]
        regres__doctor_cli___build_parser["_build_parser"]
    end
    subgraph regres__doctor_config
        regres__doctor_config___parse_env_file["_parse_env_file"]
        regres__doctor_config__DoctorConfig__print_banner_to["print_banner_to"]
        regres__doctor_config___ensure_env_file["_ensure_env_file"]
        regres__doctor_config__load_config["load_config"]
    end
    subgraph regres__import_error_toon_report
        regres__import_error_toon_report__parse_ts_errors["parse_ts_errors"]
        regres__import_error_toon_report__main["main"]
        regres__import_error_toon_report__grouped_errors["grouped_errors"]
        regres__import_error_toon_report__normalize_file_rel["normalize_file_rel"]
        regres__import_error_toon_report__to_toon_compact_per_file["to_toon_compact_per_file"]
        regres__import_error_toon_report__metrics["metrics"]
        regres__import_error_toon_report__toon_quote["toon_quote"]
        regres__import_error_toon_report__to_toon_global_payload["to_toon_global_payload"]
        regres__import_error_toon_report__render_markdown["render_markdown"]
        regres__import_error_toon_report__parse_args["parse_args"]
    end
    subgraph regres__refactor
        regres__refactor__similarity_ratio["similarity_ratio"]
        regres__refactor__main["main"]
        regres__refactor__line_count["line_count"]
        regres__refactor___render_duplicate_symbols["_render_duplicate_symbols"]
        regres__refactor___toon_files_section["_toon_files_section"]
        regres__refactor__cmd_diff["cmd_diff"]
        regres__refactor___find_md5_duplicates["_find_md5_duplicates"]
        regres__refactor___toon_meta_section["_toon_meta_section"]
        regres__refactor___render_file_symbols["_render_file_symbols"]
        regres__refactor___deps_filter_by_word["_deps_filter_by_word"]
        regres__refactor___deps_print_all["_deps_print_all"]
        regres__refactor___build_symbol_index["_build_symbol_index"]
        regres__refactor__cmd_hotmap["cmd_hotmap"]
        regres__refactor__cmd_wrappers["cmd_wrappers"]
        regres__refactor__cmd_duplicates["cmd_duplicates"]
        regres__refactor__build_parser["build_parser"]
        regres__refactor__cmd_report["cmd_report"]
        regres__refactor__normalize_code["normalize_code"]
        regres__refactor___find_duplicate_symbols["_find_duplicate_symbols"]
        regres__refactor__cmd_deps["cmd_deps"]
        regres__refactor__read_text["read_text"]
        regres__refactor__cmd_cluster["cmd_cluster"]
        regres__refactor___sanitize["_sanitize"]
        regres__refactor__get_symbols["get_symbols"]
        regres__refactor__rel["rel"]
        regres__refactor___render_cross_lang_symbols["_render_cross_lang_symbols"]
        regres__refactor__extract_symbols_ast["extract_symbols_ast"]
        regres__refactor___save_report["_save_report"]
        regres__refactor___find_external_importers["_find_external_importers"]
        regres__refactor__wrapper_score["wrapper_score"]
        regres__refactor__cmd_dead["cmd_dead"]
        regres__refactor__cmd_similar["cmd_similar"]
        regres__refactor__extract_symbols_regex["extract_symbols_regex"]
        regres__refactor___toon_similar_pairs_section["_toon_similar_pairs_section"]
        regres__refactor___format_preview["_format_preview"]
        regres__refactor___toon_clusters_section["_toon_clusters_section"]
        regres__refactor___find_name_clusters["_find_name_clusters"]
        regres__refactor___collect_file_infos["_collect_file_infos"]
        regres__refactor__iter_files["iter_files"]
        regres__refactor__extract_imports["extract_imports"]
        regres__refactor__count_word["count_word"]
        regres__refactor__cmd_symbols["cmd_symbols"]
        regres__refactor__name_prefix["name_prefix"]
        regres__refactor__to_json_toon["to_json_toon"]
        regres__refactor___format_imports["_format_imports"]
        regres__refactor__cmd_find["cmd_find"]
        regres__refactor___find_similar_pairs["_find_similar_pairs"]
        regres__refactor___deps_print_word_results["_deps_print_word_results"]
    end
    subgraph regres__regres
        regres__regres__search_missing_in_history["search_missing_in_history"]
        regres__regres__parse_numstat_block["parse_numstat_block"]
        regres__regres__find_current_locations["find_current_locations"]
        regres__regres___render_last_good_section["_render_last_good_section"]
        regres__regres__analyze_file["analyze_file"]
        regres__regres__classify_problem["classify_problem"]
        regres__regres___analyze_import_problems["_analyze_import_problems"]
        regres__regres___render_name_hash_section["_render_name_hash_section"]
        regres__regres___check_absolute_path["_check_absolute_path"]
        regres__regres__trace_name_and_hash_candidates["trace_name_and_hash_candidates"]
        regres__regres__resolve_local_import["resolve_local_import"]
        regres__regres___search_by_name_suffix["_search_by_name_suffix"]
        regres__regres__file_lineage["file_lineage"]
        regres__regres__analyze_regression["analyze_regression"]
        regres__regres___render_lineage_section["_render_lineage_section"]
        regres__regres__resolve_import_historical["resolve_import_historical"]
        regres__regres__changed_files_for_commit["changed_files_for_commit"]
        regres__regres__render_markdown["render_markdown"]
        regres__regres__resolve_target_file["resolve_target_file"]
        regres__regres__safe_read_text["safe_read_text"]
        regres__regres___render_duplicates_section["_render_duplicates_section"]
        regres__regres___render_metrics_section["_render_metrics_section"]
        regres__regres___render_references_section["_render_references_section"]
        regres__regres__content_metrics["content_metrics"]
        regres__regres___analyze_evolution["_analyze_evolution"]
        regres__regres__extract_local_imports["extract_local_imports"]
        regres__regres__dependency_tree["dependency_tree"]
        regres__regres__references_in_recent_commits["references_in_recent_commits"]
        regres__regres___render_evolution_section["_render_evolution_section"]
        regres__regres___dedupe_paths["_dedupe_paths"]
        regres__regres__reverse_references["reverse_references"]
        regres__regres__check_imports_at_commit["check_imports_at_commit"]
        regres__regres___render_classification_section["_render_classification_section"]
        regres__regres__track_filename_history["track_filename_history"]
        regres__regres___render_regression_section["_render_regression_section"]
        regres__regres__exact_and_near_duplicates["exact_and_near_duplicates"]
        regres__regres__find_repo_root["find_repo_root"]
        regres__regres___determine_primary_type["_determine_primary_type"]
        regres__regres__run_git["run_git"]
        regres__regres___check_relative_paths["_check_relative_paths"]
        regres__regres__analyze_evolution["analyze_evolution"]
        regres__regres___classify_import_problem["_classify_import_problem"]
        regres__regres__to_rel["to_rel"]
        regres__regres__find_last_working_commit["find_last_working_commit"]
        regres__regres__sha256_of_file["sha256_of_file"]
        regres__regres__file_content_at_commit["file_content_at_commit"]
        regres__regres__extract_symbols["extract_symbols"]
        regres__regres__historical_dependency_tree["historical_dependency_tree"]
    end
    subgraph regres__regres_cli
        regres__regres_cli___build_ier_argv["_build_ier_argv"]
        regres__regres_cli___append_if_true["_append_if_true"]
        regres__regres_cli__main["main"]
        regres__regres_cli___build_doctor_argv["_build_doctor_argv"]
        regres__regres_cli___build_defscan_argv["_build_defscan_argv"]
        regres__regres_cli___extend_if_set["_extend_if_set"]
    end
    subgraph regres__version_check
        regres__version_check___write_env["_write_env"]
        regres__version_check___find_env_path["_find_env_path"]
        regres__version_check__check_version["check_version"]
        regres__version_check___get_pypi_version["_get_pypi_version"]
        regres__version_check___parse_version["_parse_version"]
        regres__version_check___read_env["_read_env"]
        regres__version_check___should_check["_should_check"]
        regres__version_check___save_skip_preference["_save_skip_preference"]
        regres__version_check___is_newer["_is_newer"]
        regres__version_check___save_last_check["_save_last_check"]
    end
    regres__regres___check_relative_paths --> regres__regres___dedupe_paths
    regres__regres___search_by_name_suffix --> regres__regres___dedupe_paths
    regres__regres__resolve_target_file --> regres__regres___check_absolute_path
    regres__regres__resolve_target_file --> regres__regres___check_relative_paths
    regres__regres__resolve_target_file --> regres__regres___search_by_name_suffix
    regres__regres__content_metrics --> regres__regres__sha256_of_file
    regres__regres__check_imports_at_commit --> regres__regres__extract_local_imports
    regres__regres__check_imports_at_commit --> regres__regres__file_content_at_commit
    regres__regres__check_imports_at_commit --> regres__regres__safe_read_text
    regres__regres__find_last_working_commit --> regres__regres__check_imports_at_commit
    regres__regres__search_missing_in_history --> regres__regres__run_git
    regres__regres__analyze_regression --> regres__regres__check_imports_at_commit
    regres__regres__analyze_regression --> regres__regres__find_last_working_commit
    regres__regres__analyze_regression --> regres__regres__search_missing_in_history
    regres__regres__track_filename_history --> regres__regres__run_git
    regres__regres___classify_import_problem --> regres__regres__find_current_locations
    regres__regres___determine_primary_type --> regres__regres___analyze_evolution
    regres__regres___determine_primary_type --> regres__regres___analyze_import_problems
    regres__regres__classify_problem --> regres__regres__extract_symbols
    regres__regres__classify_problem --> regres__regres___determine_primary_type
    regres__regres__classify_problem --> regres__regres___classify_import_problem
    regres__regres__classify_problem --> regres__regres__track_filename_history
    regres__regres__dependency_tree --> regres__regres__to_rel
    regres__regres__dependency_tree --> regres__regres__safe_read_text
    regres__regres__dependency_tree --> regres__regres__resolve_local_import
    regres__regres__reverse_references --> regres__regres__to_rel
    regres__regres__reverse_references --> regres__regres__safe_read_text
    regres__regres__reverse_references --> regres__regres__resolve_local_import
    regres__regres__exact_and_near_duplicates --> regres__regres__sha256_of_file
    regres__regres__exact_and_near_duplicates --> regres__regres__safe_read_text
    regres__regres__exact_and_near_duplicates --> regres__regres__to_rel
    regres__regres__trace_name_and_hash_candidates --> regres__regres__to_rel
    regres__regres__trace_name_and_hash_candidates --> regres__regres__safe_read_text
    regres__regres__trace_name_and_hash_candidates --> regres__regres__sha256_of_file
    regres__regres__file_lineage --> regres__regres__run_git
    regres__regres__file_lineage --> regres__regres__parse_numstat_block
    regres__regres__changed_files_for_commit --> regres__regres__run_git
    regres__regres__references_in_recent_commits --> regres__regres__changed_files_for_commit
    regres__regres__file_content_at_commit --> regres__regres__run_git
    regres__regres__historical_dependency_tree --> regres__regres__file_content_at_commit
    regres__regres__historical_dependency_tree --> regres__regres__resolve_import_historical
    regres__regres__analyze_evolution --> regres__regres__file_content_at_commit
    regres__regres__analyze_evolution --> regres__regres__historical_dependency_tree
    regres__regres__render_markdown --> regres__regres___render_classification_section
    regres__regres__render_markdown --> regres__regres___render_name_hash_section
    regres__regres__render_markdown --> regres__regres___render_metrics_section
    regres__regres__render_markdown --> regres__regres___render_references_section
    regres__regres__render_markdown --> regres__regres___render_duplicates_section
    regres__regres__render_markdown --> regres__regres___render_lineage_section
    regres__regres__render_markdown --> regres__regres___render_evolution_section
    regres__regres__render_markdown --> regres__regres___render_last_good_section
    regres__regres__render_markdown --> regres__regres___render_regression_section
    regres__regres__analyze_file --> regres__regres__find_repo_root
    regres__regres__analyze_file --> regres__regres__to_rel
    regres__regres__analyze_file --> regres__regres__safe_read_text
    regres__regres__analyze_file --> regres__regres__content_metrics
    regres__regres__analyze_file --> regres__regres__dependency_tree
    regres__regres__analyze_file --> regres__regres__reverse_references
    regres__regres__analyze_file --> regres__regres__exact_and_near_duplicates
    regres__regres__analyze_file --> regres__regres__trace_name_and_hash_candidates
    regres__regres__analyze_file --> regres__regres__file_lineage
    regres__doctor_config__DoctorConfig__print_banner_to --> docs__DEFSCAN__print
    regres__doctor_config__load_config --> regres__doctor_config___ensure_env_file
    regres__doctor_config__load_config --> regres__doctor_config___parse_env_file
    regres__version_check___read_env --> regres__version_check___find_env_path
    regres__version_check___write_env --> regres__version_check___find_env_path
    regres__version_check___is_newer --> regres__version_check___parse_version
    regres__version_check___should_check --> regres__version_check___read_env
    regres__version_check___save_last_check --> regres__version_check___read_env
    regres__version_check___save_last_check --> regres__version_check___write_env
    regres__version_check___save_skip_preference --> regres__version_check___read_env
    regres__version_check___save_skip_preference --> regres__version_check___write_env
    regres__version_check__check_version --> regres__version_check___get_pypi_version
    regres__version_check__check_version --> regres__version_check___save_last_check
    regres__version_check__check_version --> regres__version_check___is_newer
    regres__version_check__check_version --> regres__version_check___should_check
    regres__version_check__check_version --> docs__DEFSCAN__print
    regres__refactor__get_symbols --> regres__refactor__extract_symbols_regex
    regres__refactor__get_symbols --> regres__refactor__extract_symbols_ast
    regres__refactor__cmd_find --> regres__refactor__iter_files
    regres__refactor__cmd_find --> docs__DEFSCAN__print
    regres__refactor__cmd_find --> regres__refactor__read_text
    regres__refactor__cmd_find --> regres__refactor__count_word
    regres__refactor__cmd_duplicates --> regres__refactor__iter_files
    regres__refactor__cmd_duplicates --> docs__DEFSCAN__print
    regres__refactor__cmd_similar --> regres__refactor__iter_files
    regres__refactor__cmd_similar --> docs__DEFSCAN__print
    regres__refactor__cmd_similar --> regres__refactor__rel
    regres__refactor___build_symbol_index --> regres__refactor__read_text
    regres__refactor___build_symbol_index --> regres__refactor__get_symbols
    regres__refactor___build_symbol_index --> regres__refactor__rel
    regres__refactor___render_cross_lang_symbols --> docs__DEFSCAN__print
    regres__refactor___render_duplicate_symbols --> docs__DEFSCAN__print
    regres__refactor___render_file_symbols --> docs__DEFSCAN__print
    regres__refactor__cmd_symbols --> regres__refactor__iter_files
    regres__refactor__cmd_symbols --> regres__refactor___build_symbol_index
    regres__refactor__cmd_symbols --> regres__refactor___render_file_symbols
    regres__refactor__cmd_symbols --> regres__refactor___render_cross_lang_symbols
    regres__refactor__cmd_wrappers --> regres__refactor__iter_files
    regres__refactor__cmd_wrappers --> docs__DEFSCAN__print
    regres__refactor__cmd_wrappers --> regres__refactor__read_text
    regres__refactor__cmd_wrappers --> regres__refactor__wrapper_score
    regres__refactor__cmd_dead --> regres__refactor__iter_files
    regres__refactor__cmd_dead --> docs__DEFSCAN__print
    regres__refactor__cmd_diff --> regres__refactor__read_text
    regres__refactor__cmd_diff --> regres__refactor__similarity_ratio
    regres__refactor__cmd_diff --> docs__DEFSCAN__print
    regres__refactor__cmd_hotmap --> regres__refactor__iter_files
    regres__refactor__cmd_hotmap --> docs__DEFSCAN__print
    regres__refactor__cmd_cluster --> regres__refactor__iter_files
    regres__refactor__cmd_cluster --> docs__DEFSCAN__print
    regres__refactor__cmd_cluster --> regres__refactor__read_text
    regres__refactor___deps_print_word_results --> docs__DEFSCAN__print
    regres__refactor___deps_print_all --> docs__DEFSCAN__print
    regres__refactor__cmd_deps --> regres__refactor__iter_files
    regres__refactor__cmd_deps --> regres__refactor__extract_imports
    regres__refactor__cmd_deps --> regres__refactor___deps_filter_by_word
    regres__refactor__cmd_deps --> regres__refactor___deps_print_word_results
    regres__refactor__cmd_deps --> regres__refactor__rel
    regres__refactor__cmd_deps --> regres__refactor__read_text
    regres__refactor__cmd_deps --> docs__DEFSCAN__print
    regres__refactor__cmd_deps --> regres__refactor___deps_print_all
    regres__refactor___format_imports --> regres__refactor___sanitize
    regres__refactor___format_preview --> regres__refactor___sanitize
    regres__refactor___toon_files_section --> regres__refactor___format_imports
    regres__refactor___toon_files_section --> regres__refactor___format_preview
    regres__refactor__to_json_toon --> regres__refactor___toon_meta_section
    regres__refactor__to_json_toon --> regres__refactor___toon_files_section
    regres__refactor__to_json_toon --> regres__refactor___toon_clusters_section
    regres__refactor__to_json_toon --> regres__refactor___toon_similar_pairs_section
    regres__refactor___collect_file_infos --> regres__refactor__read_text
    regres__refactor___collect_file_infos --> regres__refactor__count_word
    regres__refactor___collect_file_infos --> regres__refactor__get_symbols
    regres__refactor___collect_file_infos --> regres__refactor__wrapper_score
    regres__refactor___collect_file_infos --> regres__refactor__rel
    regres__refactor___collect_file_infos --> regres__refactor__line_count
    regres__refactor___find_name_clusters --> regres__refactor__name_prefix
    regres__refactor___find_similar_pairs --> regres__refactor__normalize_code
    regres__refactor___find_duplicate_symbols --> regres__refactor__read_text
    regres__refactor___find_duplicate_symbols --> regres__refactor__get_symbols
    regres__refactor___find_duplicate_symbols --> regres__refactor__rel
    regres__refactor___find_external_importers --> regres__refactor__iter_files
    regres__refactor___find_external_importers --> regres__refactor__rel
    regres__refactor___find_external_importers --> regres__refactor__extract_imports
    regres__refactor___find_external_importers --> regres__refactor__read_text
    regres__refactor___save_report --> regres__refactor__to_json_toon
    regres__refactor___save_report --> docs__DEFSCAN__print
    regres__refactor__cmd_report --> docs__DEFSCAN__print
    regres__refactor__cmd_report --> regres__refactor__iter_files
    regres__refactor__cmd_report --> regres__refactor___collect_file_infos
    regres__refactor__cmd_report --> regres__refactor___find_md5_duplicates
    regres__refactor__cmd_report --> regres__refactor___find_name_clusters
    regres__refactor__cmd_report --> regres__refactor___find_similar_pairs
    regres__refactor__cmd_report --> regres__refactor___find_duplicate_symbols
    regres__refactor__main --> regres__refactor__build_parser
    regres__refactor__main --> docs__DEFSCAN__print
    regres__import_error_toon_report__parse_ts_errors --> regres__import_error_toon_report__normalize_file_rel
    regres__import_error_toon_report__to_toon_global_payload --> regres__import_error_toon_report__grouped_errors
    regres__import_error_toon_report__to_toon_global_payload --> regres__import_error_toon_report__metrics
    regres__import_error_toon_report__to_toon_compact_per_file --> regres__import_error_toon_report__toon_quote
    regres__import_error_toon_report__render_markdown --> regres__import_error_toon_report__grouped_errors
    regres__import_error_toon_report__render_markdown --> regres__import_error_toon_report__metrics
    regres__import_error_toon_report__render_markdown --> regres__import_error_toon_report__to_toon_global_payload
    regres__import_error_toon_report__render_markdown --> regres__import_error_toon_report__to_toon_compact_per_file
    regres__import_error_toon_report__main --> regres__version_check__check_version
    regres__import_error_toon_report__main --> regres__import_error_toon_report__parse_args
    regres__import_error_toon_report__main --> regres__import_error_toon_report__parse_ts_errors
    regres__import_error_toon_report__main --> regres__import_error_toon_report__render_markdown
    regres__import_error_toon_report__main --> docs__DEFSCAN__print
    regres__regres_cli__main --> regres__version_check__check_version
    regres__regres_cli___build_defscan_argv --> regres__regres_cli___extend_if_set
    regres__regres_cli___build_defscan_argv --> regres__regres_cli___append_if_true
    regres__regres_cli___build_doctor_argv --> regres__regres_cli___extend_if_set
    regres__regres_cli___build_doctor_argv --> regres__regres_cli___append_if_true
    regres__regres_cli___build_ier_argv --> regres__regres_cli___extend_if_set
    regres__defscan__Definition____init__ --> regres__defscan___normalize
    regres__defscan___extract_class_definitions --> regres__defscan___get_body
    regres__defscan___extract_class_definitions --> regres__defscan___get_decorators
    regres__defscan___extract_function_definition --> regres__defscan___get_body
    regres__defscan___extract_function_definition --> regres__defscan___get_decorators
    regres__defscan__extract_python --> regres__defscan___collect_class_method_ids
    regres__defscan__extract_python --> regres__defscan___extract_class_definitions
    regres__defscan___extract_block_ts --> regres__defscan___advance_past_string
    regres__defscan___extract_block_ts --> regres__defscan___advance_past_comment
    regres__defscan__extract_typescript --> regres__defscan___lineno_at
    regres__defscan__extract_typescript --> regres__defscan___extract_block_ts
    regres__defscan__extract_go --> regres__defscan___extract_block_ts
    regres__defscan__extract_go --> regres__defscan___lineno_at
    regres__defscan__extract_rust --> regres__defscan___extract_block_ts
    regres__defscan__extract_rust --> regres__defscan___lineno_at
    regres__defscan__extract_file --> regres__defscan__extract_python
    regres__defscan__extract_file --> docs__DEFSCAN__print
    regres__defscan__extract_file --> regres__defscan__extract_typescript
    regres__defscan__extract_file --> regres__defscan__extract_go
    regres__defscan__extract_file --> regres__defscan__extract_rust
    regres__defscan___path_ignored_by_gitignore --> regres__defscan___match_anchored_pattern
    regres__defscan___path_ignored_by_gitignore --> regres__defscan___match_unanchored_pattern
    regres__defscan___should_skip_file --> regres__defscan___path_ignored_by_gitignore
    regres__defscan__scan --> regres__defscan__load_gitignore
    regres__defscan__scan --> regres__defscan___should_skip_file
    regres__defscan__scan --> regres__defscan__extract_file
    regres__defscan__compare_seed_to_all --> regres__defscan___def_key
    regres__defscan__compare_seed_to_all --> regres__defscan__sim
    regres__defscan__analyse_group --> regres__defscan__sim
    regres__defscan__render_text --> regres__defscan__c
    regres__defscan__render_seed_text --> regres__defscan__c
    regres__defscan__render_seed_markdown --> regres__defscan___short_path
    regres__defscan__render_seed_json --> regres__defscan___short_path
    regres__defscan__render_seed_json --> regres__defscan__classify_similarity
    regres__defscan__render_json --> regres__defscan__classify_similarity
    regres__defscan__render_json --> regres__defscan___short_path
    regres__defscan___run_seed_mode --> docs__DEFSCAN__print
    regres__defscan___run_seed_mode --> regres__defscan__scan
    regres__defscan___run_seed_mode --> regres__defscan__compare_seed_to_all
    regres__defscan___build_focus_groups --> regres__defscan___def_key
    regres__defscan___analyse_and_sort_groups --> regres__defscan__analyse_group
    regres__defscan___run_focus_mode --> docs__DEFSCAN__print
    regres__defscan___run_focus_mode --> regres__defscan__scan
    regres__defscan___run_focus_mode --> regres__defscan___build_focus_groups
    regres__defscan___run_focus_mode --> regres__defscan___analyse_and_sort_groups
    regres__defscan___run_default_mode --> docs__DEFSCAN__print
    regres__defscan___run_default_mode --> regres__defscan__scan
    regres__defscan___run_default_mode --> regres__defscan___print_pair_summary
    regres__defscan___run_default_mode --> regres__defscan__analyse_group
    regres__defscan___print_pair_summary --> docs__DEFSCAN__print
    regres__defscan___print_pair_summary --> regres__defscan___count_similarity_levels
    regres__defscan__main --> regres__defscan___build_argument_parser
    regres__defscan__main --> regres__defscan__load_gitignore
    regres__defscan__main --> docs__DEFSCAN__print
    regres__defscan__main --> regres__defscan___run_seed_mode
    regres__doctor_cli___run_llm_or_targeted_analysis --> docs__DEFSCAN__print
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___run_page_implementation_analysis
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___run_module_loader_compliance_check
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___run_page_registry_compliance_check
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___collect_dependency_chain_targets
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___run_llm_or_targeted_analysis
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___run_dependency_chain_analysis
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___derive_vite_base
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___create_import_chain_diagnoses
    regres__doctor_cli___run_url_module_analysis --> regres__doctor_cli___run_vite_runtime_probe
    regres__doctor_cli___handle_runtime_log_diagnostics --> regres__doctor_cli___resolve_runtime_log_path
    regres__doctor_cli___handle_url_mode --> regres__doctor_cli___resolve_module_from_url
    regres__doctor_cli___handle_url_mode --> regres__doctor_cli___record_url_discovery_step
    regres__doctor_cli___handle_url_mode --> regres__doctor_cli___setup_url_analysis_context
    regres__doctor_cli___handle_url_mode --> regres__doctor_cli___handle_module_resolution
    regres__doctor_cli___handle_url_mode --> regres__doctor_cli___apply_fixes_if_requested
    regres__doctor_cli___setup_url_analysis_context --> regres__doctor_cli___handle_runtime_log_diagnostics
    regres__doctor_cli___handle_module_resolution --> regres__doctor_cli___record_module_resolution_step
    regres__doctor_cli___handle_module_resolution --> regres__doctor_cli___record_module_not_found_step
    regres__doctor_cli___handle_module_resolution --> regres__doctor_cli___append_url_module_not_found_diagnosis
    regres__doctor_cli___handle_module_resolution --> regres__doctor_cli___run_url_module_analysis
    regres__doctor_cli___apply_fixes_if_requested --> docs__DEFSCAN__print
    regres__doctor_cli___handle_auto_decision_flow --> regres__doctor_cli___handle_runtime_log_diagnostics
    regres__doctor_cli___save_report --> docs__DEFSCAN__print
    regres__doctor_cli___refresh_import_error_log --> docs__DEFSCAN__print
    regres__doctor_cli__main --> regres__version_check__check_version
    regres__doctor_cli__main --> regres__doctor_cli___build_parser
    regres__doctor_cli__main --> regres__doctor_config__load_config
    regres__doctor_cli__main --> regres__doctor_cli___handle_auto_decision_flow
    regres__doctor_cli__main --> regres__doctor_cli___save_report
